### ISSUE TITLE
Unable to inject TextMapPropagator into Tracer

### ISSUE THREAD

**Issue by mchandramouli** [ExpediaDotCom/haystack-client-node#28]
Issue reported by Jatin Kumar Nim.  Unable to inject TextMapPropagator instances into traces to use extract/inject methods to use custom header names.

**Comment by mchandramouli** [comment]
@ashishagg  https://github.com/ExpediaDotCom/haystack-client-node/pull/29/

**Comment by ashishagg** [comment]
Fixed in version 0.2.2. Closing this.
